[package]
name = "elucitools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elucidator = { path = "../elucidator" }
clap = { version = "4.5.16", features = ["derive"] }
