[workspace]

members = [
    "elucidator",
    "elucidator-db",
    "elucitools",
    "elucidator_macros",
    "elucidatorc",
    "pyelucidator",
]
resolver = "2"

[profile.release-with-debug]
inherits = "release"
debug = true
