[workspace]

members = [
    "elucidator",
    "elucidator-db",
    "elucitools",
    "elucidator_macros", "elucidatorc",
]
resolver = "2"

[profile.release-with-debug]
inherits = "release"
debug = true
