[package]
name = "elucidator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elucidator_macros = { path = "../elucidator_macros" }

[dev-dependencies]
rand = "0.8.5"
