[package]
name = "monte_carlo"
version = "0.1.0"
edition = "2021"

[dependencies]
elucidator = { version = "0.1.0", path = "../../../elucidator" }
elucidator-db = { version = "0.1.0", path = "../../../elucidator-db" }
rand = "0.8.5"
