[package]
name = "scratch-rusqlite"
version = "0.1.0"
edition = "2021"

[dependencies]
elucidator = { version = "0.1.0", path = "../elucidator" }
rusqlite = { version = "0.32.1", features = ["backup"] }
