[package]
name = "my_crate_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0.68", features = ["extra-traits"] }
quote = "1.0"
proc-macro2 = "1.0.86"

